Meet/Meet/Models/CarMeet.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Metadata;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Meet.Models
{
    public class CarMeet
    {
        [Key]
        public int MeetId { get; set; }
        [Display(Name = "Meet Name")]
        public string MeetName { get; set; }
        public double Lat { get; set; }
        public double Long { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public long Zip { get; set; }
        [Display(Name = "Meet Time")]
        public DateTimeOffset MeetTime { get; set; }
        [Display(Name = "Meet Date")]
        public DateTimeOffset MeetDate { get; set; }

        [ForeignKey("IdentityUser")]
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }
    }
}

Meet/Meet/Controllers/CarMeetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Meet.Data;
using Meet.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http;
using Newtonsoft.Json.Linq;
using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Meet.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using NuGet.Protocol;
using Newtonsoft.Json;

namespace Meet.Controllers
{
    [Authorize(Roles = "CarGuy")]

    public class CarMeetsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CarMeetsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CarMeets
        public async Task<IActionResult> Index()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var client = _context.Clients.Where(c => c.IdentityUserId == userId).FirstOrDefault();

            var address = client.City.ToString() + "%20" + client.State.ToString();
            var httpClient = new HttpClient();

            using HttpResponseMessage response = await httpClient.GetAsync("https://maps.googleapis.com/maps/api/geocode/json?address=" + address + $"&key={Meet.ApiKeys.GoogleApiKey}");
            response.EnsureSuccessStatusCode();
            string responseBody = await response.Content.ReadAsStringAsync();
            var geocode = JsonConvert.DeserializeObject<GeocodeJson>(responseBody).Results;

            var carMeets = _context.CarMeets;
            if (carMeets == null)
            {
                return RedirectToAction("Create");
            }
            var applicationDbContext = _context.CarMeets.Where(x => x.State == client.State).Select(x => new CarMeetListRecord{
                MeetDate = x.MeetDate.DateTime.ToShortDateString(),
                MeetId = x.MeetId,
                MeetName = x.MeetName,
                MeetTime = x.MeetTime.DateTime.ToShortTimeString(),
                Lat = x.Lat, 
                Long = x.Long,
                City = x.City,
                Zip = x.Zip,
                State = x.State,
                Street = x.Street,
                UserLat = geocode[0].geometry.location.lat,
                UserLong = geocode[0].geometry.location.lng,
            });
            var result = await applicationDbContext.ToListAsync(); 
            return View(result);
        }

        public IActionResult SOS(int? id)
        {
            var meet = _context.CarMeets.Where(c => c.MeetId == id).FirstOrDefault();
            if (id != null)
            {
               TwilioClient.Init(ApiKeys.TwilioAccountSid, ApiKeys.TwilioAuthToken);
                var clientMeet = _context.ClientMeets.Where(c => c.MeetId == id);
                
                foreach(var item in clientMeet)
                {
                    var tempClient = _context.Clients.Where(c => c.ClientId == item.ClientId).FirstOrDefault();
                    var message = MessageResource.Create(
                                body: $"There are police at {meet.MeetName} in {meet.City}, {meet.State.ToUpper()}.",
                                from: new Twilio.Types.PhoneNumber(ApiKeys.TwilioPhoneNumber),
                                to: new Twilio.Types.PhoneNumber($"+1{tempClient.PhoneNumber}")
                            );
                }
                return RedirectToAction("Details", new { id = meet.MeetId });

            }
            return RedirectToAction("Details", new {id = meet.MeetId});
        }
    
        public IActionResult RSVPIndex(int id)
        {

            var rsvps = _context.ClientMeets.Where(c => c.MeetId == id).ToList();
            if (rsvps == null)
            {
                return RedirectToAction("Index");
            }
            List<RSVPClient> clients = new List<RSVPClient>();
            Dictionary<int,bool> cars = new Dictionary<int,bool>();
            foreach (var item in rsvps)
            {
                var client = _context.Clients.Where(c => c.ClientId == item.ClientId).Select(x => new RSVPClient
                {
                    Age = x.Age,
                    City = x.City,
                    ClientId = x.ClientId,
                    IdentityUser = x.IdentityUser,
                    IdentityUserId = x.IdentityUserId,
                    FirstName = x.FirstName,
                    LastName = x.LastName,
                    PhoneNumber = x.PhoneNumber,
                    MeetId = item.MeetId,
                }).FirstOrDefault();
                var car = _context.Cars.Where(c => c.IdentityUserId == client.IdentityUserId).FirstOrDefault();
                if(car != null)
                {
                    client.HasCar = true;
                }
                else
                {
                    client.HasCar = false;
                }
                clients.Add(client);
            }
            if(clients.Count == 0) { clients.Add(new RSVPClient() { MeetId = id }); }
            return View(clients);
        }
        public async Task<IActionResult> CommentIndex(int id)
        {
            var exisitingComments = await _context.Comments.Where(c => c.MeetId == id).Select(x => new CommentDetail
            {
                CommentBody = x.CommentBody,
                CommentId = x.CommentId,
                CommentorsName = x.CommentorsName,
                Date = x.Date,
                IsOwner = false,
                MeetId = x.MeetId
            }).ToListAsync();
            var carMeet = await _context.CarMeets.Where(c => c.MeetId == id).FirstOrDefaultAsync();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var client = await _context.Clients.Where(c => c.IdentityUserId == userId).FirstOrDefaultAsync();
            var clientName = (client.FirstName + " " + client.LastName).ToLower();
            List<CommentDetail> comments = new List<CommentDetail>();
            if (exisitingComments.Count() == 0)
            {
                comments.Add(new CommentDetail() { MeetId = id });
            }
            else
            {
                foreach(var item in exisitingComments)
                {
                    if (item.CommentorsName.ToLower() == clientName)
                    {
                        item.IsOwner = true;
                    }
                    comments.Add(item);
                }
            }
            return View( comments);
        }

        // GET: Comments/Create
        public IActionResult CommentCreate(CarMeet carMeet, int? id)
        {
            Comment comment = new Comment();
            if(carMeet.MeetId == 0)
            {
                comment.MeetId = (int)id;
            }
            else
            {
                comment.MeetId = carMeet.MeetId;
            }
            
            return View(comment);
        }

        // POST: Comments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CommentCreate([Bind("CommentId,CommentorsName,CommentBody,Date,MeetId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var client = _context.Clients.Where(c => c.IdentityUserId == userId).FirstOrDefault();
                comment.CommentorsName = $"{client.FirstName} {client.LastName}";
                comment.Date = DateTime.Now.ToString("M/d/yyyy");
                _context.Add(comment);
                await _context.SaveChangesAsync();
                return RedirectToAction("CommentIndex", new {id = comment.MeetId});
            }
            return View(comment);
        }
        // GET: CarMeets/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var identityId = User.Claims.ToList()[0].Value;

            var currentUser = await _context.Clients.Where(x => x.IdentityUserId == identityId).FirstOrDefaultAsync();
            if (id == null)
            {
                return NotFound();
            }
            var carMeet = await _context.CarMeets.Where(x => x.MeetId == id).Select(x => new CarMeetDetails
            {
                MeetDate = x.MeetDate.DateTime.ToShortDateString(),
                MeetId = x.MeetId,
                MeetName = x.MeetName,
                MeetTime = x.MeetTime.DateTime.ToShortTimeString(),
                City = x.City,
                CurrentUserId = currentUser.ClientId,
                State = x.State,
                Street = x.Street,
                Zip = x.Zip,
                IsRSVP = false,
                Lat = x.Lat,
                Long = x.Long,
                CreatedBy = x.IdentityUserId,
                IsOwner = false,
            }).FirstOrDefaultAsync();

            if(carMeet.CreatedBy == identityId) { carMeet.IsOwner = true; }
            var clientMeet = await _context.ClientMeets.Where(x => x.MeetId == carMeet.MeetId && x.ClientId == currentUser.ClientId).FirstOrDefaultAsync();

            if (clientMeet != null) { carMeet.IsRSVP = true; }

            if (carMeet == null)
            {
                return NotFound();
            }
            return View(carMeet);
        }

        // GET: CarMeets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CarMeets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

Meet/Meet/Views/CarMeets/CommentCreate.cshtml
@model Meet.Models.Comment

@{
    ViewData["Title"] = "CommentCreate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create a comment</h1>

<h4>New Comment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CommentCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="CommentBody" class="control-label"></label>
                <input asp-for="CommentBody" class="form-control" />
                <span asp-validation-for="CommentBody" class="text-danger"></span>
            </div>
            
            <input type="hidden" asp-for="MeetId" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Meet/Meet/Views/CarMeets/CommentIndex.cshtml
@model IEnumerable<Meet.ViewModels.CommentDetail>

@{
    ViewData["Title"] = "CommentIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    #meetButtons{
        margin-bottom: 15px;
    }

    #alert {
        background-color: red;
        border-color: red;
    }
    #commentCard{
        margin-bottom: 10px;
    }
</style>
<h1>Comments</h1>
<a type="button" asp-controller="CarMeets" asp-action="Details" asp-route-id="@Model.ElementAt(0).MeetId" class="btn btn-primary" id="meetButtons">Back To The Meet</a>
@if(Model.ElementAt(0).MeetId != 0 && Model.ElementAt(0).CommentId != 0)
{
    @foreach(var item in Model)
    {
        <div class="card text-center" id="commentCard">
            <div class="card-header text-center">
                @Html.DisplayFor(modelItem => item.CommentorsName)
                <div class="text-center">
                    @if (item.IsOwner)
                    {
                        <a type="button" class="btn btn-danger text-center btn-sm btn-block">Delete Placeholder</a>
                    }
                </div>
            </div>
            <div class="card-body">
                <p class="card-text">@Html.DisplayFor(modelItem => item.CommentBody)</p>
            </div>
            <div class="card-footer text-muted">
                @Html.DisplayFor(modelItem => item.Date)
            </div>
        </div>
    }
    <a type="button" class="btn btn-primary" asp-action="CommentCreate" asp-route-id="@Model.ElementAt(0).MeetId">Create A New Comment!</a>
}
else{
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Comment Section</h1>
        <p class="lead">No comments have been submitted for this meet yet</p>
        <p>Want to be the first to comment?</p><a type="button" class="btn btn-primary" asp-action="CommentCreate" asp-route-id="@Model.ElementAt(0).MeetId">Create A New Comment!</a>
    </div>
</div>
}

Meet/Meet/Views/CarMeets/Create.cshtml
@model Meet.Models.CarMeet

@{
    ViewData["Title"] = "Create A Meet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create a new Meet</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetName" class="control-label"></label>
                <input asp-for="MeetName" class="form-control" />
                <span asp-validation-for="MeetName" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" MaxLength="2" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zip" class="control-label"></label>
                <input asp-for="Zip" class="form-control" />
                <span asp-validation-for="Zip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeetTime" class="control-label"></label>
                <input asp-for="MeetTime" class="form-control" type="time"/>
                <span asp-validation-for="MeetTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MeetDate" class="control-label"></label>
                <input asp-for="MeetDate" class="form-control" type="date" />
                <span asp-validation-for="MeetDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Meet/Meet/Views/CarMeets/Delete.cshtml
@model Meet.Models.CarMeet

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CarMeet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Long)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Long)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MeetDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MeetDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MeetId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Meet/Meet/Views/CarMeets/Index.cshtml
@model IEnumerable<Meet.ViewModels.CarMeetListRecord>
@{
    ViewData["Title"] = "Meets";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Meets</h1>
<style>
    .table-hover tbody tr:hover td {
        background: lightgray;
    }
    </style>
<p id="inlineButtons">
    <table class="table">
        <tr>
            <th>
                <div class="input-group input-group-sm mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroup-sizing-sm">Want to explore Meets in a different area?</span>
                    </div>
                    <input type="number" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm" placeholder="Zipcode" maxlength="5" id="zipCodeInput">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" onclick="searchByZip(document.getElementById('zipCodeInput').value)" onkeypress="searchByZip(document.getElementById('zipCodeInput').value)">Search</button>
                    </div>
                </div>
            </th>
            <th>
                <a type="button" class="btn btn-primary btn-group-sm" asp-controller="CarMeets" asp-action="Create" >Create A New Meet</a>
            </th>
        </tr>
    </table>
    
    
    
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">
                @Html.DisplayNameFor(model => model.MeetName)
            </th>
        
            <th scope="col">
                @Html.DisplayNameFor(model => model.Street)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Zip)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.MeetTime)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.MeetDate)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="location.href = '@Url.Action("Details", "CarMeets", new { id=item.MeetId })'" title="Click to show details.">
                <td scope="row">
                    @Html.DisplayFor(modelItem => item.MeetName)
                </td>
             
                <td>
                    @Html.DisplayFor(modelItem => item.Street)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Zip)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MeetTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MeetDate)
                </td>
            </tr>
        }
    </tbody>
</table>

<style type="text/css">
    /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
    #map {
        height: 400px;
    }

    /* Optional: Makes the sample page fill the window. */
    html,
    body {
        height: 100%;
        margin: 0;
        padding: 0;
    }

    #description {
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
    }

    #infowindow-content .title {
        font-weight: bold;
    }

    #infowindow-content {
        display: none;
    }

    #map #infowindow-content {
        display: inline;
    }

    .pac-card {
        margin: 10px 10px 0 0;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        background-color: #fff;
        font-family: Roboto;
    }

    #pac-container {
        padding-bottom: 12px;
        margin-right: 12px;
    }

    .pac-controls {
        display: inline-block;
        padding: 5px 11px;
    }

        .pac-controls label {
            font-family: Roboto;
            font-size: 13px;
            font-weight: 300;
        }

    #pac-input {
        background-color: #fff;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        margin-left: 12px;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 400px;
    }

        #pac-input:focus {
            border-color: #4d90fe;
        }

    #title {
        color: #fff;
        background-color: #4d90fe;
        font-size: 25px;
        font-weight: 500;
        padding: 6px 12px;
    }

    #target {
        width: 345px;
    }

    .gm-style-iw + button {
        display: none;
        border: none;
    }

    .gm-style-iw button:focus {
        outline: 0;
    }
</style>
<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
<script async="false" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=@Meet.ApiKeys.GoogleApiKey&callback=initMap&libraries=&v=weekly"></script>

<script>

    var myLatLng = { lat: 35.227085, lng: -80.843124 };
    var useBrowserLocation = false;
    var zipState = '';
    var useSearchByZip = false;
    var browserCoords = {};
    navigator.geolocation.getCurrentPosition(showPosition, positionError);
    function showPosition(position) {
        var coords = position.coords;
        browserCoords = { lat: coords.latitude, lng: coords.longitude };
        useBrowserLocation = true;
        console.log('showposotion true', browserCoords);
        initMap();
    }
    function positionError(position) {
        console.log('showposition false')
        useBrowserLocation = false;
        initMap();
    }
    function isInfoWindowOpen(infoWindow) {
        var map = infoWindow.getMap();
        return (map !== null && typeof map !== "undefined");
    }

    function searchByZip(zipCode) {
        console.log('zip', zipCode)
        document.getElementById('zipCodeInput').value = ""
        geocoder.geocode({ 'address': zipCode.toString() }, function (results, status) {
            if (status == 'OK') {
                console.log('help results', results, zipCode)
                myLatLng = { lat: results[0].geometry.location.lat(), lng: results[0].geometry.location.lng()}
                // zipState = results[0].address_components[3].short_name.toString();
                console.log('lat lnmg', myLatLng, zipState)
                useSearchByZip = true;
                initMap();
            } else {
                alert('Geocode was not successful for the following reason: ' + status);
            }
        });
    }

    function initMap() {
        if (google) {
            geocoder = new google.maps.Geocoder();
        }
        var meet = @Html.Raw(Json.Serialize(Model.FirstOrDefault()));


        if (!useSearchByZip) {
            if (useBrowserLocation) {
                myLatLng = browserCoords;
            }
            else {
                if (meet != null) {
                    console.log('hit')
                    myLatLng = { lat: meet.userLat, lng: meet.userLong };
                }
            }
        }

        const map = new google.maps.Map(document.getElementById("map"), {
            zoom: 11,
            center: myLatLng,
        });
        const infoWindow = new google.maps.InfoWindow();
 
        var meets = @Html.Raw(Json.Serialize(Model));
        if (meets.length != 0) {
            for (let i = 0; i < meets.length; i++) {
                var meet = meets[i];
                // if (useSearchByZip) {
                //     if (meet.state == zipState) {
                //         var Latitude = meet.lat;
                //         var Longitude = meet.long;
                //         var label = (i + 1).toString();
                //         myLatLng = { lat: Latitude, lng: Longitude }
                //         const marker = new google.maps.Marker({
                //             position: myLatLng,
                //             map,
                //             title: meet.meetName,
                //             label: label
                //         });
                //         marker.addListener("click", () => {
                //             if (isInfoWindowOpen(infoWindow)) {
                //                 infoWindow.close();

                //             }
                //             else {
                //                 infoWindow.close();
                //                 infoWindow.setContent(marker.getTitle());
                //                 infoWindow.open(marker.getMap(), marker);
                //                 infoWindow.focus(marker)
                //             }

                //         });
                //     }
                // }
                // else {
                    var Latitude = meet.lat;
                    var Longitude = meet.long;
                    var label = (i + 1).toString();
                    myLatLng = { lat: Latitude, lng: Longitude }
                    const marker = new google.maps.Marker({
                        position: myLatLng,
                        map,
                        title: meet.meetName,
                        label: label
                    });
                    marker.addListener("click", () => {
                        if (isInfoWindowOpen(infoWindow)) {
                            infoWindow.close();

                        }
                        else {
                            infoWindow.close();
                            infoWindow.setContent(marker.getTitle());
                            infoWindow.open(marker.getMap(), marker);
                            infoWindow.focus(marker)
                        }

                    });
                //}
                
            }
        }
    }
</script>
    <body>

        <div id="map"></div>
    </body>

Meet/Meet/Views/CarMeets/RSVPIndex.cshtml
@model IEnumerable<Meet.ViewModels.RSVPClient>



@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>RSVP's</h1>
<style>
    .container .jumbotron {
        border-radius: 6px;
    }
</style>
@if(Model.ElementAt(0).MeetId != 0 && Model.ElementAt(0).ClientId != 0)
{
    <div>
    <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>

                    @if (item.HasCar)
                    {
                        <a type="button" asp-controller="Cars" asp-action="ClientDetails" asp-route-id="@item.ClientId" class="btn btn-primary">View Car</a>
                    }
                    else
                    {
                        <a type="button" style="pointer-events: none" class="btn btn-warning">No Car</a>
                    }

                <a type="button" asp-controller="Clients" asp-action="AddFriend" asp-route-id="@item.ClientId" class="btn btn-primary">Add Friend</a>
            </td>
        </tr>
        }
    </tbody>
</table>
</div>
    <a type="button" asp-controller="CarMeets" asp-action="Details" asp-route-id="@Model.ElementAt(0).MeetId" class="btn btn-primary">Back To The Meet</a>
}
else
{
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-4">RSVP's</h1>
            <p class="lead">No RSVP's found</p>
        </div>
    </div>
    <a type="button" asp-controller="CarMeets" asp-action="Details" asp-route-id="@Model.ElementAt(0).MeetId" class="btn btn-primary">Back To The Meet</a>
}